# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "onetwenty"
license = ""
licenselink = ""
description = ""
homepage = ""
tags = []
features = []
min_version = "0.20"

[author]
  name = "Craig Bilner"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
